let bundles=[];
const money=n=>`GH₵ ${Number(n).toFixed(2)}`;
async function api(url,options={}){const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed');return data}
async function loadBundles(){try{bundles=await api('/api/bundles');renderBundles()}catch(e){showToast(e.message)}}
function renderBundles(){const grid=document.getElementById('bundleGrid');if(!grid)return;const groups={};for(const b of bundles)(groups[b.network]??=[]).push(b);grid.innerHTML=Object.entries(groups).map(([network,plans])=>{const cls=network==='MTN'?'mtn':network==='AirtelTigo'?'at':'telecel';return `<article class="bundle-card"><div class="bundle-head ${cls}"><span>${network}</span><small>${network==='MTN'?'Better Together':network==='AirtelTigo'?'Live More':'Tomorrow Together'}</small></div><div class="plans">${plans.map(b=>`<button class="plan" onclick="openPurchase('${b.id}','${network}','${b.name}',${b.price})"><b>${b.name}</b><span>${money(b.price)}</span></button>`).join('')}</div><button class="buy-btn" onclick="openPurchase('${plans[0].id}','${network}','${plans[0].name}',${plans[0].price})">Buy Now</button></article>`}).join('')}
async function openPurchase(bundleId,network,bundleName,price){let me=null;try{me=await api('/api/auth/me')}catch{}openModal(`<h2>Buy ${bundleName} ${network} Data</h2><p class="muted">Enter the number that should receive the bundle.</p><form class="form" onsubmit="createOrder(event,'${bundleId}','${network}','${bundleName}',${price})"><label>Mobile Number<input id="recipientPhone" required pattern="[0-9]{10}" value="${me?.user?.phone||''}" placeholder="0241234567" inputmode="numeric"></label><label>Email for payment receipt<input id="paymentEmail" type="email" required value="${me?.user?.email||''}" placeholder="you@example.com"></label><div class="notice">Amount to pay: <b>${money(price)}</b><br>You will receive a mobile-money authorization prompt.</div><button class="btn btn-yellow">Continue to MoMo Payment →</button></form>`)}
async function createOrder(e,bundleId,network,bundleName,price){e.preventDefault();try{const me=await api('/api/auth/me')}catch{openLogin();return}try{const order=await api('/api/orders',{method:'POST',body:JSON.stringify({bundleId,recipientPhone:document.getElementById('recipientPhone').value})});await startMomo(order.order.id,document.getElementById('paymentEmail').value,network); }catch(err){showToast(err.message)}}
async function startMomo(orderId,email,network){try{const provider=network==='MTN'?'mtn':network==='AirtelTigo'?'atl':'vod';const result=await api('/api/payments/paystack/momo',{method:'POST',body:JSON.stringify({orderId,email,provider})});openModal(`<h2>Approve Payment</h2><div class="notice"><b>${result.displayText||'Approve the payment on your phone.'}</b><br><br>Reference: <b>${result.reference}</b><br>This request expires if not authorized within the provider's allowed time.</div><button class="btn btn-yellow" onclick="verifyPayment('${result.reference}')">I Have Approved — Check Payment</button>`)}catch(err){openModal(`<h2>Payment could not start</h2><div class="notice">${err.message}</div>`)} }
async function verifyPayment(reference){try{const r=await api('/api/payments/paystack/verify/'+encodeURIComponent(reference));if(r.status==='success'){openModal(`<h2>Payment Successful ✓</h2><div class="success-message">Your payment has been verified. Your order is now queued for fulfilment.<br><br>Reference: <b>${reference}</b></div>`)}else{showToast('Payment status: '+r.status);}}catch(e){showToast(e.message)}}
function openLogin(){openModal(`<h2>Customer Login</h2><form class="form" onsubmit="login(event)"><label>Email<input id="loginEmail" type="email" required></label><label>Password<input id="loginPassword" type="password" required></label><button class="btn btn-yellow">Login</button></form><p class="muted">New customer? <a href="#" onclick="openRegister();return false">Create an account</a></p>`)}
async function login(e){e.preventDefault();try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:loginEmail.value,password:loginPassword.value})});closeModal();showToast(`Welcome ${r.user.name}`)}catch(err){showToast(err.message)}}
function openRegister(){openModal(`<h2>Create Account</h2><form class="form" onsubmit="register(event)"><label>Full Name<input id="regName" required></label><label>Phone<input id="regPhone" required pattern="[0-9]{10}"></label><label>Email<input id="regEmail" type="email" required></label><label>Password<input id="regPassword" type="password" minlength="8" required></label><button class="btn btn-yellow">Create Account</button></form>`)}
async function register(e){e.preventDefault();try{const r=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:regName.value,phone:regPhone.value,email:regEmail.value,password:regPassword.value})});closeModal();showToast(`Account created for ${r.user.name}`)}catch(err){showToast(err.message)}}
function openModal(html){document.getElementById('modalContent').innerHTML=html;document.getElementById('modal').classList.add('open')}
function closeModal(){document.getElementById('modal').classList.remove('open')}
function showToast(msg){const t=document.getElementById('toast');if(!t)return; t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function showService(name){showToast(`${name} integration can be added through the same secure order/payment API.`)}
async function loadAdmin(){if(!document.getElementById('adminRoot'))return;try{const me=await api('/api/auth/me');if(me.user.role!=='ADMIN')throw new Error('Administrator access required');const [stats,orders]=await Promise.all([api('/api/admin/stats'),api('/api/orders')]);document.getElementById('statSales').textContent=money(stats.totalSales);document.getElementById('statOrders').textContent=stats.orders;document.getElementById('statPending').textContent=stats.pendingSales;document.getElementById('statCustomers').textContent=stats.customers;renderAdminOrders(orders)}catch(e){document.getElementById('adminRoot').innerHTML=`<div class="admin-card"><h2>Admin Login Required</h2><p>${e.message}</p><a class="btn btn-yellow" href="index.html">Go to customer site</a><button class="btn btn-outline" onclick="adminLogin()">Admin Login</button></div>`}}
function adminLogin(){openModal(`<h2>Administrator Login</h2><form class="form" onsubmit="doAdminLogin(event)"><label>Email<input id="adminEmail" type="email" required></label><label>Password<input id="adminPassword" type="password" required></label><button class="btn btn-yellow">Login</button></form>`)}
async function doAdminLogin(e){e.preventDefault();try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:adminEmail.value,password:adminPassword.value})});closeModal();location.reload()}catch(err){showToast(err.message)}}
function renderAdminOrders(orders){const body=document.getElementById('ordersBody');if(!body)return;body.innerHTML=orders.map(o=>`<tr><td>${o.reference}</td><td>${o.user?.email||''}</td><td>${o.bundle.network}</td><td>${o.bundle.name}</td><td>${money(o.amount)}</td><td>${o.paymentStatus}</td><td><span class="status ${o.status==='DELIVERED'?'success':o.status==='PAID'?'success':'pending'}">${o.status}</span></td></tr>`).join('')||'<tr><td colspan="7">No orders yet.</td></tr>'}
async function exportOrders(){try{const orders=await api('/api/orders');const rows=[['Reference','Customer','Network','Bundle','Amount','Payment','Status'],...orders.map(o=>[o.reference,o.user?.email||'',o.bundle.network,o.bundle.name,o.amount,o.paymentStatus,o.status])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='legacy-orders.csv';a.click()}catch(e){showToast(e.message)}}
document.addEventListener('DOMContentLoaded',()=>{loadBundles();loadAdmin();document.querySelector('.menu-toggle')?.addEventListener('click',()=>document.getElementById('mainNav')?.classList.toggle('open'));document.getElementById('modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()})});
